Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "pure-archive-245518"
    google.google_json_key_location = "/Users/bruno/tmp/chave.json"

    google.machine_type = "f1-micro"
    google.zone = "us-central1-a"
    google.image_family = "ubuntu-2204-lts"

    override.ssh.username = "vagrant"
    override.ssh.private_key_path = ["~/.ssh/vagrant_google_key"]

    google.metadata = {
      "ssh-keys" => "vagrant:#{File.read(File.expand_path('~/.ssh/vagrant_google_key.pub'))}"
    }
  end
  
end