Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider :virtualbox do |vb|
    vb.name = "my_vm"
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.synced_folder "./local_guelo", "/guelo"
  config.vm.network "private_network", type: "dhcp"
  #config.vm.network "public_network"
end